name: voice_assistant
description: Речевой ассистент с шумоподавлением и адаптацией к акцентам.
publish_to: 'none' # Не публиковать в pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # TensorFlow Lite для Flutter
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.1

  # Работа с аудио
  flutter_sound: ^9.2.13
  permission_handler: ^10.0.0
  path_provider: ^2.0.11

  # Обработка сигналов
  fftea: ^1.2.0

  # UI компоненты
  cupertino_icons: ^1.0.5
  provider: ^6.0.3
  shared_preferences: ^2.0.15

  # Для преобразования аудио данных
  flutter_isolate: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/models/